name: wasm_wit_component_example
description: Demonstrates how to use the wasm_wit_component package.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  wasm_run:
    path: ../../../wasm_run
  wasm_wit_component:
    path: ../
  test: ^1.26.0
  dart_style: ^2.3.6

dev_dependencies:
  very_good_analysis: ^6.0.0
