name: wasm_wit_component_example
description: Demonstrates how to use the wasm_wit_component package.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.0
resolution: workspace

dependencies:
  wasm_run:
    path: ../../../wasm_run
  wasm_wit_component:
    path: ../
  test: ^1.21.0
  dart_style: ^2.3.0

dev_dependencies:
  very_good_analysis: ^10.0.0
