name: rust_crypto
description: Hashes, Hmacs, Argon2 Passwords and AES-GCM-SIV encryption. Digests for sha1, sha2, md5, blake3, crc32
version: 0.2.0
repository: https://github.com/juancastillo0/wasm_run
topics:
  - wasm
  - wit
  - crypto
  - password
  - encryption

environment:
  sdk: ^3.10.0
resolution: workspace
flutter:
  assets:
    - lib/assets/

dependencies:
  wasm_run: ^0.2.0
  wasm_wit_component: ^0.2.0

dev_dependencies:
  cryptography: ^2.5.0
  crypto: ^3.0.3
  webcrypto: ^0.6.0
  # r_crypto: ^0.5.0
  # cryptography_flutter: ^2.3.0

  # dargon2: ^3.2.1 https://github.com/tmthecoder/dargon2/issues/27
  argon2: ^1.0.1

  # aes_gcm
  pointycastle: ^3.7.3
  hashlib: ^2.3.0 # benchmark https://pub.dev/packages/hashlib
  # Blake3

  lints: ^6.1.0
  test: ^1.30.0
