// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class EnvVariable {
  /// The name of the environment variable
  final String name;

  /// The value of the environment variable
  final String value;

  const EnvVariable({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnvVariable &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

class ModuleConfig {
  /// Is `true` if the [`multi-value`] Wasm proposal is enabled.
  final bool? multiValue;

  /// Is `true` if the [`bulk-memory`] Wasm proposal is enabled.
  final bool? bulkMemory;

  /// Is `true` if the [`reference-types`] Wasm proposal is enabled.
  final bool? referenceTypes;

  /// Is `true` if executions shall consume fuel.
  final bool? consumeFuel;

  /// Configuration specific to the wasmi runtime
  final ModuleConfigWasmi? wasmi;

  /// Configuration specific to the wasmtime runtime
  final ModuleConfigWasmtime? wasmtime;

  const ModuleConfig({
    this.multiValue,
    this.bulkMemory,
    this.referenceTypes,
    this.consumeFuel,
    this.wasmi,
    this.wasmtime,
  });

  @override
  int get hashCode =>
      multiValue.hashCode ^
      bulkMemory.hashCode ^
      referenceTypes.hashCode ^
      consumeFuel.hashCode ^
      wasmi.hashCode ^
      wasmtime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModuleConfig &&
          runtimeType == other.runtimeType &&
          multiValue == other.multiValue &&
          bulkMemory == other.bulkMemory &&
          referenceTypes == other.referenceTypes &&
          consumeFuel == other.consumeFuel &&
          wasmi == other.wasmi &&
          wasmtime == other.wasmtime;
}

class ModuleConfigWasmi {
  /// The limits set on the value stack and call stack.
  final WasiStackLimits? stackLimits;

  /// The amount of Wasm stacks to keep in cache at most.
  final PlatformInt64? cachedStacks;

  /// Is `true` if the `mutable-global` Wasm proposal is enabled.
  final bool? mutableGlobal;

  /// Is `true` if the `sign-extension` Wasm proposal is enabled.
  final bool? signExtension;

  /// Is `true` if the `saturating-float-to-int` Wasm proposal is enabled.
  final bool? saturatingFloatToInt;

  /// Is `true` if the [`tail-call`] Wasm proposal is enabled.
  final bool? tailCall;

  /// Is `true` if the [`extended-const`] Wasm proposal is enabled.
  final bool? extendedConst;

  /// Is `true` if Wasm instructions on `f32` and `f64` types are allowed.
  final bool? floats;

  const ModuleConfigWasmi({
    this.stackLimits,
    this.cachedStacks,
    this.mutableGlobal,
    this.signExtension,
    this.saturatingFloatToInt,
    this.tailCall,
    this.extendedConst,
    this.floats,
  });

  @override
  int get hashCode =>
      stackLimits.hashCode ^
      cachedStacks.hashCode ^
      mutableGlobal.hashCode ^
      signExtension.hashCode ^
      saturatingFloatToInt.hashCode ^
      tailCall.hashCode ^
      extendedConst.hashCode ^
      floats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModuleConfigWasmi &&
          runtimeType == other.runtimeType &&
          stackLimits == other.stackLimits &&
          cachedStacks == other.cachedStacks &&
          mutableGlobal == other.mutableGlobal &&
          signExtension == other.signExtension &&
          saturatingFloatToInt == other.saturatingFloatToInt &&
          tailCall == other.tailCall &&
          extendedConst == other.extendedConst &&
          floats == other.floats;
}

class ModuleConfigWasmtime {
  /// Configures whether DWARF debug information will be emitted during
  /// compilation.
  final bool? debugInfo;
  final bool? wasmBacktrace;
  final bool? nativeUnwindInfo;
  final PlatformInt64? maxWasmStack;

  /// Whether or not to enable the `threads` WebAssembly feature.
  /// This includes atomics and shared memory as well.
  /// This is not enabled by default.
  final bool? wasmThreads;

  /// Whether or not to enable the `simd` WebAssembly feature.
  final bool? wasmSimd;

  /// Whether or not to enable the `relaxed-simd` WebAssembly feature.
  /// This is not enabled by default.
  final bool? wasmRelaxedSimd;

  /// Whether [wasm_relaxed_simd] should be deterministic.
  /// This is false by default.
  final bool? relaxedSimdDeterministic;

  /// Whether or not to enable the `multi-memory` WebAssembly feature.
  /// This is not enabled by default.
  final bool? wasmMultiMemory;

  /// Whether or not to enable the `memory64` WebAssembly feature.
  /// This is not enabled by default.
  final bool? wasmMemory64;
  final BigInt? staticMemoryMaximumSize;
  final bool? staticMemoryForced;
  final BigInt? staticMemoryGuardSize;
  final bool? parallelCompilation;
  final bool? generateAddressMap;

  const ModuleConfigWasmtime({
    this.debugInfo,
    this.wasmBacktrace,
    this.nativeUnwindInfo,
    this.maxWasmStack,
    this.wasmThreads,
    this.wasmSimd,
    this.wasmRelaxedSimd,
    this.relaxedSimdDeterministic,
    this.wasmMultiMemory,
    this.wasmMemory64,
    this.staticMemoryMaximumSize,
    this.staticMemoryForced,
    this.staticMemoryGuardSize,
    this.parallelCompilation,
    this.generateAddressMap,
  });

  @override
  int get hashCode =>
      debugInfo.hashCode ^
      wasmBacktrace.hashCode ^
      nativeUnwindInfo.hashCode ^
      maxWasmStack.hashCode ^
      wasmThreads.hashCode ^
      wasmSimd.hashCode ^
      wasmRelaxedSimd.hashCode ^
      relaxedSimdDeterministic.hashCode ^
      wasmMultiMemory.hashCode ^
      wasmMemory64.hashCode ^
      staticMemoryMaximumSize.hashCode ^
      staticMemoryForced.hashCode ^
      staticMemoryGuardSize.hashCode ^
      parallelCompilation.hashCode ^
      generateAddressMap.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModuleConfigWasmtime &&
          runtimeType == other.runtimeType &&
          debugInfo == other.debugInfo &&
          wasmBacktrace == other.wasmBacktrace &&
          nativeUnwindInfo == other.nativeUnwindInfo &&
          maxWasmStack == other.maxWasmStack &&
          wasmThreads == other.wasmThreads &&
          wasmSimd == other.wasmSimd &&
          wasmRelaxedSimd == other.wasmRelaxedSimd &&
          relaxedSimdDeterministic == other.relaxedSimdDeterministic &&
          wasmMultiMemory == other.wasmMultiMemory &&
          wasmMemory64 == other.wasmMemory64 &&
          staticMemoryMaximumSize == other.staticMemoryMaximumSize &&
          staticMemoryForced == other.staticMemoryForced &&
          staticMemoryGuardSize == other.staticMemoryGuardSize &&
          parallelCompilation == other.parallelCompilation &&
          generateAddressMap == other.generateAddressMap;
}

/// A preopened directory that the WASM module will be able to access
class PreopenedDir {
  /// The path inside the WASM module.
  /// Should be "/" separated, if you are on windows, you will need to convert the path
  final String wasmGuestPath;

  /// The path on the host that the WASM module will be able to access
  /// and corresponds to the [wasm_guest_path]
  final String hostPath;

  const PreopenedDir({required this.wasmGuestPath, required this.hostPath});

  @override
  int get hashCode => wasmGuestPath.hashCode ^ hostPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreopenedDir &&
          runtimeType == other.runtimeType &&
          wasmGuestPath == other.wasmGuestPath &&
          hostPath == other.hostPath;
}

enum StdIOKind { stdout, stderr }

class WasiConfigNative {
  /// Whether to capture stdout.
  /// If this is true, you can use the [WasmInstance.stdout]
  /// getter to retrieve a stream of the module's stdout.
  final bool captureStdout;

  /// Whether to capture stderr
  /// If this is true, you can use the [WasmInstance.stderr]
  /// getter to retrieve a stream of the module's stderr.
  final bool captureStderr;

  /// Whether to inherit stdin from the host process.
  final bool inheritStdin;

  /// Whether to inherit environment variables from the host process.
  final bool inheritEnv;

  /// Whether to inherit the process arguments from the host process.
  final bool inheritArgs;

  /// Custom process arguments to pass to the WASM module
  final List<String> args;

  /// Custom Environment variables to pass to the WASM module
  final List<EnvVariable> env;

  /// Custom preopened files to pass to the WASM module
  final List<String> preopenedFiles;

  /// Custom preopened directories to pass to the WASM module
  /// The module will be able to access and edit these directories
  final List<PreopenedDir> preopenedDirs;

  const WasiConfigNative({
    required this.captureStdout,
    required this.captureStderr,
    required this.inheritStdin,
    required this.inheritEnv,
    required this.inheritArgs,
    required this.args,
    required this.env,
    required this.preopenedFiles,
    required this.preopenedDirs,
  });

  @override
  int get hashCode =>
      captureStdout.hashCode ^
      captureStderr.hashCode ^
      inheritStdin.hashCode ^
      inheritEnv.hashCode ^
      inheritArgs.hashCode ^
      args.hashCode ^
      env.hashCode ^
      preopenedFiles.hashCode ^
      preopenedDirs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WasiConfigNative &&
          runtimeType == other.runtimeType &&
          captureStdout == other.captureStdout &&
          captureStderr == other.captureStderr &&
          inheritStdin == other.inheritStdin &&
          inheritEnv == other.inheritEnv &&
          inheritArgs == other.inheritArgs &&
          args == other.args &&
          env == other.env &&
          preopenedFiles == other.preopenedFiles &&
          preopenedDirs == other.preopenedDirs;
}

/// The configured limits of the Wasm stack.
class WasiStackLimits {
  /// The initial value stack height that the Wasm stack prepares.
  final PlatformInt64 initialValueStackHeight;

  /// The maximum value stack height in use that the Wasm stack allows.
  final PlatformInt64 maximumValueStackHeight;

  /// The maximum number of nested calls that the Wasm stack allows.
  final PlatformInt64 maximumRecursionDepth;

  const WasiStackLimits({
    required this.initialValueStackHeight,
    required this.maximumValueStackHeight,
    required this.maximumRecursionDepth,
  });

  @override
  int get hashCode =>
      initialValueStackHeight.hashCode ^
      maximumValueStackHeight.hashCode ^
      maximumRecursionDepth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WasiStackLimits &&
          runtimeType == other.runtimeType &&
          initialValueStackHeight == other.initialValueStackHeight &&
          maximumValueStackHeight == other.maximumValueStackHeight &&
          maximumRecursionDepth == other.maximumRecursionDepth;
}

/// https://docs.wasmtime.dev/stability-wasm-proposals-support.html
class WasmFeatures {
  /// The WebAssembly `mutable-global` proposal (enabled by default)
  final bool mutableGlobal;

  /// The WebAssembly `nontrapping-float-to-int-conversions` proposal (enabled by default)
  final bool saturatingFloatToInt;

  /// The WebAssembly `sign-extension-ops` proposal (enabled by default)
  final bool signExtension;

  /// The WebAssembly reference types proposal (enabled by default)
  final bool referenceTypes;

  /// The WebAssembly multi-value proposal (enabled by default)
  final bool multiValue;

  /// The WebAssembly bulk memory operations proposal (enabled by default)
  final bool bulkMemory;

  /// The WebAssembly SIMD proposal
  final bool simd;

  /// The WebAssembly Relaxed SIMD proposal
  final bool relaxedSimd;

  /// The WebAssembly threads proposal, shared memory and atomics
  /// https://docs.rs/wasmtime/14.0.4/wasmtime/struct.Config.html#method.wasm_threads
  final bool threads;

  /// The WebAssembly tail-call proposal
  final bool tailCall;

  /// Whether or not floating-point instructions are enabled.
  ///
  /// This is enabled by default can be used to disallow floating-point
  /// operators and types.
  ///
  /// This does not correspond to a WebAssembly proposal but is instead
  /// intended for embeddings which have stricter-than-usual requirements
  /// about execution. Floats in WebAssembly can have different NaN patterns
  /// across hosts which can lead to host-dependent execution which some
  /// runtimes may not desire.
  final bool floats;

  /// The WebAssembly multi memory proposal
  final bool multiMemory;

  /// The WebAssembly exception handling proposal
  final bool exceptions;

  /// The WebAssembly memory64 proposal
  final bool memory64;

  /// The WebAssembly extended_const proposal
  final bool extendedConst;

  /// The WebAssembly component model proposal
  final bool componentModel;

  /// The WebAssembly memory control proposal
  final bool memoryControl;

  /// The WebAssembly garbage collection (GC) proposal
  final bool garbageCollection;

  /// WebAssembly external types reflection or, for browsers,
  /// the js-types proposal (https://github.com/WebAssembly/js-types/blob/main/proposals/js-types/Overview.md)
  final bool typeReflection;

  /// The WebAssembly System Interface proposal
  final WasmWasiFeatures? wasiFeatures;

  const WasmFeatures({
    required this.mutableGlobal,
    required this.saturatingFloatToInt,
    required this.signExtension,
    required this.referenceTypes,
    required this.multiValue,
    required this.bulkMemory,
    required this.simd,
    required this.relaxedSimd,
    required this.threads,
    required this.tailCall,
    required this.floats,
    required this.multiMemory,
    required this.exceptions,
    required this.memory64,
    required this.extendedConst,
    required this.componentModel,
    required this.memoryControl,
    required this.garbageCollection,
    required this.typeReflection,
    this.wasiFeatures,
  });

  @override
  int get hashCode =>
      mutableGlobal.hashCode ^
      saturatingFloatToInt.hashCode ^
      signExtension.hashCode ^
      referenceTypes.hashCode ^
      multiValue.hashCode ^
      bulkMemory.hashCode ^
      simd.hashCode ^
      relaxedSimd.hashCode ^
      threads.hashCode ^
      tailCall.hashCode ^
      floats.hashCode ^
      multiMemory.hashCode ^
      exceptions.hashCode ^
      memory64.hashCode ^
      extendedConst.hashCode ^
      componentModel.hashCode ^
      memoryControl.hashCode ^
      garbageCollection.hashCode ^
      typeReflection.hashCode ^
      wasiFeatures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WasmFeatures &&
          runtimeType == other.runtimeType &&
          mutableGlobal == other.mutableGlobal &&
          saturatingFloatToInt == other.saturatingFloatToInt &&
          signExtension == other.signExtension &&
          referenceTypes == other.referenceTypes &&
          multiValue == other.multiValue &&
          bulkMemory == other.bulkMemory &&
          simd == other.simd &&
          relaxedSimd == other.relaxedSimd &&
          threads == other.threads &&
          tailCall == other.tailCall &&
          floats == other.floats &&
          multiMemory == other.multiMemory &&
          exceptions == other.exceptions &&
          memory64 == other.memory64 &&
          extendedConst == other.extendedConst &&
          componentModel == other.componentModel &&
          memoryControl == other.memoryControl &&
          garbageCollection == other.garbageCollection &&
          typeReflection == other.typeReflection &&
          wasiFeatures == other.wasiFeatures;
}

class WasmRuntimeFeatures {
  /// The name of the runtime.
  /// For example, "wasmi" or "wasmtime".
  final String name;

  /// The version of the runtime.
  /// For example, "0.31.0" or "14.0.4".
  final String version;

  /// Is `true` if the runtime is the one provided by the browser.
  final bool isBrowser;

  /// The features supported by the runtime.
  final WasmFeatures supportedFeatures;

  /// The default features of the runtime.
  /// If a feature is supported, but it is not enable by default,
  /// then it must be enabled manually, perhaps with [ModuleConfig],
  /// and it may be experimental.
  final WasmFeatures defaultFeatures;

  const WasmRuntimeFeatures({
    required this.name,
    required this.version,
    required this.isBrowser,
    required this.supportedFeatures,
    required this.defaultFeatures,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      version.hashCode ^
      isBrowser.hashCode ^
      supportedFeatures.hashCode ^
      defaultFeatures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WasmRuntimeFeatures &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          version == other.version &&
          isBrowser == other.isBrowser &&
          supportedFeatures == other.supportedFeatures &&
          defaultFeatures == other.defaultFeatures;
}

/// https://docs.wasmtime.dev/stability-wasi-proposals-support.html
class WasmWasiFeatures {
  /// Access to standard input, output, and error streams
  final bool io;

  /// Access to the filesystem
  final bool filesystem;

  /// Access to clocks and the system time
  final bool clocks;

  /// Access to random number generators
  final bool random;
  final bool poll;

  /// wasi-nn
  final bool machineLearning;

  /// wasi-crypto
  final bool crypto;

  /// WASM threads with ability to spawn
  /// https://github.com/WebAssembly/wasi-threads
  final bool threads;

  const WasmWasiFeatures({
    required this.io,
    required this.filesystem,
    required this.clocks,
    required this.random,
    required this.poll,
    required this.machineLearning,
    required this.crypto,
    required this.threads,
  });

  @override
  int get hashCode =>
      io.hashCode ^
      filesystem.hashCode ^
      clocks.hashCode ^
      random.hashCode ^
      poll.hashCode ^
      machineLearning.hashCode ^
      crypto.hashCode ^
      threads.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WasmWasiFeatures &&
          runtimeType == other.runtimeType &&
          io == other.io &&
          filesystem == other.filesystem &&
          clocks == other.clocks &&
          random == other.random &&
          poll == other.poll &&
          machineLearning == other.machineLearning &&
          crypto == other.crypto &&
          threads == other.threads;
}
