// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:wasm_run/src/rust/api.dart';
import 'package:wasm_run/src/rust/atomics.dart';
import 'package:wasm_run/src/rust/config.dart';
import 'package:wasm_run/src/rust/frb_generated.dart';
import 'package:wasm_run/src/rust/lib.dart';
import 'package:wasm_run/src/rust/types.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcRwLockSharedMemoryPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_ArcRwLockSharedMemory;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcMutexModulePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_ArcstdsyncMutexModule;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CallStackPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_CallStack;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_GlobalPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_Global;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MemoryPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_Memory;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TablePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_Table;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_WFuncPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_WFunc;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ArcRwLockSharedMemory dco_decode_RustOpaque_ArcRwLockSharedMemory(
    dynamic raw,
  );

  @protected
  ArcMutexModule dco_decode_RustOpaque_ArcstdsyncMutexModule(dynamic raw);

  @protected
  CallStack dco_decode_RustOpaque_CallStack(dynamic raw);

  @protected
  Global dco_decode_RustOpaque_Global(dynamic raw);

  @protected
  Memory dco_decode_RustOpaque_Memory(dynamic raw);

  @protected
  Table dco_decode_RustOpaque_Table(dynamic raw);

  @protected
  WFunc dco_decode_RustOpaque_WFunc(dynamic raw);

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Dco(
    dynamic raw,
  );

  @protected
  RustStreamSink<ParallelExec> dco_decode_StreamSink_parallel_exec_Dco(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Num dco_decode_TraitDef_Num(dynamic raw);

  @protected
  AtomicKind dco_decode_atomic_kind(dynamic raw);

  @protected
  AtomicOrdering dco_decode_atomic_ordering(dynamic raw);

  @protected
  Atomics dco_decode_atomics(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  WFunc dco_decode_box_autoadd_RustOpaque_WFunc(dynamic raw);

  @protected
  Atomics dco_decode_box_autoadd_atomics(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CompiledModule dco_decode_box_autoadd_compiled_module(dynamic raw);

  @protected
  FuncTy dco_decode_box_autoadd_func_ty(dynamic raw);

  @protected
  FunctionCall dco_decode_box_autoadd_function_call(dynamic raw);

  @protected
  GlobalTy dco_decode_box_autoadd_global_ty(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MemoryTy dco_decode_box_autoadd_memory_ty(dynamic raw);

  @protected
  ModuleConfig dco_decode_box_autoadd_module_config(dynamic raw);

  @protected
  ModuleConfigWasmi dco_decode_box_autoadd_module_config_wasmi(dynamic raw);

  @protected
  ModuleConfigWasmtime dco_decode_box_autoadd_module_config_wasmtime(
    dynamic raw,
  );

  @protected
  TableArgs dco_decode_box_autoadd_table_args(dynamic raw);

  @protected
  TableTy dco_decode_box_autoadd_table_ty(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  WasiConfigNative dco_decode_box_autoadd_wasi_config_native(dynamic raw);

  @protected
  WasiStackLimits dco_decode_box_autoadd_wasi_stack_limits(dynamic raw);

  @protected
  WasmRunInstanceId dco_decode_box_autoadd_wasm_run_instance_id(dynamic raw);

  @protected
  WasmRunModuleId dco_decode_box_autoadd_wasm_run_module_id(dynamic raw);

  @protected
  WasmRunSharedMemory dco_decode_box_autoadd_wasm_run_shared_memory(
    dynamic raw,
  );

  @protected
  WasmVal dco_decode_box_autoadd_wasm_val(dynamic raw);

  @protected
  WasmWasiFeatures dco_decode_box_autoadd_wasm_wasi_features(dynamic raw);

  @protected
  CompareExchangeResult dco_decode_compare_exchange_result(dynamic raw);

  @protected
  CompiledModule dco_decode_compiled_module(dynamic raw);

  @protected
  EnvVariable dco_decode_env_variable(dynamic raw);

  @protected
  ExternalType dco_decode_external_type(dynamic raw);

  @protected
  ExternalValue dco_decode_external_value(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FuncTy dco_decode_func_ty(dynamic raw);

  @protected
  FunctionCall dco_decode_function_call(dynamic raw);

  @protected
  GlobalTy dco_decode_global_ty(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<EnvVariable> dco_decode_list_env_variable(dynamic raw);

  @protected
  List<ModuleExportDesc> dco_decode_list_module_export_desc(dynamic raw);

  @protected
  List<ModuleExportValue> dco_decode_list_module_export_value(dynamic raw);

  @protected
  List<ModuleImport> dco_decode_list_module_import(dynamic raw);

  @protected
  List<ModuleImportDesc> dco_decode_list_module_import_desc(dynamic raw);

  @protected
  List<PreopenedDir> dco_decode_list_preopened_dir(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ValueTy> dco_decode_list_value_ty(dynamic raw);

  @protected
  List<WasmVal> dco_decode_list_wasm_val(dynamic raw);

  @protected
  MemoryTy dco_decode_memory_ty(dynamic raw);

  @protected
  ModuleConfig dco_decode_module_config(dynamic raw);

  @protected
  ModuleConfigWasmi dco_decode_module_config_wasmi(dynamic raw);

  @protected
  ModuleConfigWasmtime dco_decode_module_config_wasmtime(dynamic raw);

  @protected
  ModuleExportDesc dco_decode_module_export_desc(dynamic raw);

  @protected
  ModuleExportValue dco_decode_module_export_value(dynamic raw);

  @protected
  ModuleImport dco_decode_module_import(dynamic raw);

  @protected
  ModuleImportDesc dco_decode_module_import_desc(dynamic raw);

  @protected
  WFunc? dco_decode_opt_box_autoadd_RustOpaque_WFunc(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ModuleConfigWasmi? dco_decode_opt_box_autoadd_module_config_wasmi(
    dynamic raw,
  );

  @protected
  ModuleConfigWasmtime? dco_decode_opt_box_autoadd_module_config_wasmtime(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  WasiConfigNative? dco_decode_opt_box_autoadd_wasi_config_native(dynamic raw);

  @protected
  WasiStackLimits? dco_decode_opt_box_autoadd_wasi_stack_limits(dynamic raw);

  @protected
  WasmVal? dco_decode_opt_box_autoadd_wasm_val(dynamic raw);

  @protected
  WasmWasiFeatures? dco_decode_opt_box_autoadd_wasm_wasi_features(dynamic raw);

  @protected
  ParallelExec dco_decode_parallel_exec(dynamic raw);

  @protected
  PointerAndLength dco_decode_pointer_and_length(dynamic raw);

  @protected
  PreopenedDir dco_decode_preopened_dir(dynamic raw);

  @protected
  SharedMemoryWaitResult dco_decode_shared_memory_wait_result(dynamic raw);

  @protected
  StdIOKind dco_decode_std_io_kind(dynamic raw);

  @protected
  TableArgs dco_decode_table_args(dynamic raw);

  @protected
  TableTy dco_decode_table_ty(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  U8Array16 dco_decode_u_8_array_16(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ValueTy dco_decode_value_ty(dynamic raw);

  @protected
  WasiConfigNative dco_decode_wasi_config_native(dynamic raw);

  @protected
  WasiStackLimits dco_decode_wasi_stack_limits(dynamic raw);

  @protected
  WasmFeatures dco_decode_wasm_features(dynamic raw);

  @protected
  WasmRunInstanceId dco_decode_wasm_run_instance_id(dynamic raw);

  @protected
  WasmRunModuleId dco_decode_wasm_run_module_id(dynamic raw);

  @protected
  WasmRunSharedMemory dco_decode_wasm_run_shared_memory(dynamic raw);

  @protected
  WasmRuntimeFeatures dco_decode_wasm_runtime_features(dynamic raw);

  @protected
  WasmVal dco_decode_wasm_val(dynamic raw);

  @protected
  WasmWasiFeatures dco_decode_wasm_wasi_features(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ArcRwLockSharedMemory sse_decode_RustOpaque_ArcRwLockSharedMemory(
    SseDeserializer deserializer,
  );

  @protected
  ArcMutexModule sse_decode_RustOpaque_ArcstdsyncMutexModule(
    SseDeserializer deserializer,
  );

  @protected
  CallStack sse_decode_RustOpaque_CallStack(SseDeserializer deserializer);

  @protected
  Global sse_decode_RustOpaque_Global(SseDeserializer deserializer);

  @protected
  Memory sse_decode_RustOpaque_Memory(SseDeserializer deserializer);

  @protected
  Table sse_decode_RustOpaque_Table(SseDeserializer deserializer);

  @protected
  WFunc sse_decode_RustOpaque_WFunc(SseDeserializer deserializer);

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Dco(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ParallelExec> sse_decode_StreamSink_parallel_exec_Dco(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AtomicKind sse_decode_atomic_kind(SseDeserializer deserializer);

  @protected
  AtomicOrdering sse_decode_atomic_ordering(SseDeserializer deserializer);

  @protected
  Atomics sse_decode_atomics(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  WFunc sse_decode_box_autoadd_RustOpaque_WFunc(SseDeserializer deserializer);

  @protected
  Atomics sse_decode_box_autoadd_atomics(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CompiledModule sse_decode_box_autoadd_compiled_module(
    SseDeserializer deserializer,
  );

  @protected
  FuncTy sse_decode_box_autoadd_func_ty(SseDeserializer deserializer);

  @protected
  FunctionCall sse_decode_box_autoadd_function_call(
    SseDeserializer deserializer,
  );

  @protected
  GlobalTy sse_decode_box_autoadd_global_ty(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MemoryTy sse_decode_box_autoadd_memory_ty(SseDeserializer deserializer);

  @protected
  ModuleConfig sse_decode_box_autoadd_module_config(
    SseDeserializer deserializer,
  );

  @protected
  ModuleConfigWasmi sse_decode_box_autoadd_module_config_wasmi(
    SseDeserializer deserializer,
  );

  @protected
  ModuleConfigWasmtime sse_decode_box_autoadd_module_config_wasmtime(
    SseDeserializer deserializer,
  );

  @protected
  TableArgs sse_decode_box_autoadd_table_args(SseDeserializer deserializer);

  @protected
  TableTy sse_decode_box_autoadd_table_ty(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WasiConfigNative sse_decode_box_autoadd_wasi_config_native(
    SseDeserializer deserializer,
  );

  @protected
  WasiStackLimits sse_decode_box_autoadd_wasi_stack_limits(
    SseDeserializer deserializer,
  );

  @protected
  WasmRunInstanceId sse_decode_box_autoadd_wasm_run_instance_id(
    SseDeserializer deserializer,
  );

  @protected
  WasmRunModuleId sse_decode_box_autoadd_wasm_run_module_id(
    SseDeserializer deserializer,
  );

  @protected
  WasmRunSharedMemory sse_decode_box_autoadd_wasm_run_shared_memory(
    SseDeserializer deserializer,
  );

  @protected
  WasmVal sse_decode_box_autoadd_wasm_val(SseDeserializer deserializer);

  @protected
  WasmWasiFeatures sse_decode_box_autoadd_wasm_wasi_features(
    SseDeserializer deserializer,
  );

  @protected
  CompareExchangeResult sse_decode_compare_exchange_result(
    SseDeserializer deserializer,
  );

  @protected
  CompiledModule sse_decode_compiled_module(SseDeserializer deserializer);

  @protected
  EnvVariable sse_decode_env_variable(SseDeserializer deserializer);

  @protected
  ExternalType sse_decode_external_type(SseDeserializer deserializer);

  @protected
  ExternalValue sse_decode_external_value(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FuncTy sse_decode_func_ty(SseDeserializer deserializer);

  @protected
  FunctionCall sse_decode_function_call(SseDeserializer deserializer);

  @protected
  GlobalTy sse_decode_global_ty(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<EnvVariable> sse_decode_list_env_variable(SseDeserializer deserializer);

  @protected
  List<ModuleExportDesc> sse_decode_list_module_export_desc(
    SseDeserializer deserializer,
  );

  @protected
  List<ModuleExportValue> sse_decode_list_module_export_value(
    SseDeserializer deserializer,
  );

  @protected
  List<ModuleImport> sse_decode_list_module_import(
    SseDeserializer deserializer,
  );

  @protected
  List<ModuleImportDesc> sse_decode_list_module_import_desc(
    SseDeserializer deserializer,
  );

  @protected
  List<PreopenedDir> sse_decode_list_preopened_dir(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ValueTy> sse_decode_list_value_ty(SseDeserializer deserializer);

  @protected
  List<WasmVal> sse_decode_list_wasm_val(SseDeserializer deserializer);

  @protected
  MemoryTy sse_decode_memory_ty(SseDeserializer deserializer);

  @protected
  ModuleConfig sse_decode_module_config(SseDeserializer deserializer);

  @protected
  ModuleConfigWasmi sse_decode_module_config_wasmi(
    SseDeserializer deserializer,
  );

  @protected
  ModuleConfigWasmtime sse_decode_module_config_wasmtime(
    SseDeserializer deserializer,
  );

  @protected
  ModuleExportDesc sse_decode_module_export_desc(SseDeserializer deserializer);

  @protected
  ModuleExportValue sse_decode_module_export_value(
    SseDeserializer deserializer,
  );

  @protected
  ModuleImport sse_decode_module_import(SseDeserializer deserializer);

  @protected
  ModuleImportDesc sse_decode_module_import_desc(SseDeserializer deserializer);

  @protected
  WFunc? sse_decode_opt_box_autoadd_RustOpaque_WFunc(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ModuleConfigWasmi? sse_decode_opt_box_autoadd_module_config_wasmi(
    SseDeserializer deserializer,
  );

  @protected
  ModuleConfigWasmtime? sse_decode_opt_box_autoadd_module_config_wasmtime(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  WasiConfigNative? sse_decode_opt_box_autoadd_wasi_config_native(
    SseDeserializer deserializer,
  );

  @protected
  WasiStackLimits? sse_decode_opt_box_autoadd_wasi_stack_limits(
    SseDeserializer deserializer,
  );

  @protected
  WasmVal? sse_decode_opt_box_autoadd_wasm_val(SseDeserializer deserializer);

  @protected
  WasmWasiFeatures? sse_decode_opt_box_autoadd_wasm_wasi_features(
    SseDeserializer deserializer,
  );

  @protected
  ParallelExec sse_decode_parallel_exec(SseDeserializer deserializer);

  @protected
  PointerAndLength sse_decode_pointer_and_length(SseDeserializer deserializer);

  @protected
  PreopenedDir sse_decode_preopened_dir(SseDeserializer deserializer);

  @protected
  SharedMemoryWaitResult sse_decode_shared_memory_wait_result(
    SseDeserializer deserializer,
  );

  @protected
  StdIOKind sse_decode_std_io_kind(SseDeserializer deserializer);

  @protected
  TableArgs sse_decode_table_args(SseDeserializer deserializer);

  @protected
  TableTy sse_decode_table_ty(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  U8Array16 sse_decode_u_8_array_16(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ValueTy sse_decode_value_ty(SseDeserializer deserializer);

  @protected
  WasiConfigNative sse_decode_wasi_config_native(SseDeserializer deserializer);

  @protected
  WasiStackLimits sse_decode_wasi_stack_limits(SseDeserializer deserializer);

  @protected
  WasmFeatures sse_decode_wasm_features(SseDeserializer deserializer);

  @protected
  WasmRunInstanceId sse_decode_wasm_run_instance_id(
    SseDeserializer deserializer,
  );

  @protected
  WasmRunModuleId sse_decode_wasm_run_module_id(SseDeserializer deserializer);

  @protected
  WasmRunSharedMemory sse_decode_wasm_run_shared_memory(
    SseDeserializer deserializer,
  );

  @protected
  WasmRuntimeFeatures sse_decode_wasm_runtime_features(
    SseDeserializer deserializer,
  );

  @protected
  WasmVal sse_decode_wasm_val(SseDeserializer deserializer);

  @protected
  WasmWasiFeatures sse_decode_wasm_wasi_features(SseDeserializer deserializer);

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String cst_encode_StreamSink_list_prim_u_8_strict_Dco(
    RustStreamSink<Uint8List> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_prim_u_8_strict,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  String cst_encode_StreamSink_parallel_exec_Dco(
    RustStreamSink<ParallelExec> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_parallel_exec,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_atomics(Atomics raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_usize(raw.field0)].jsify()!;
  }

  @protected
  int cst_encode_box_autoadd_RustOpaque_WFunc(WFunc raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_RustOpaque_WFunc(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_atomics(Atomics raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_atomics(raw);
  }

  @protected
  bool cst_encode_box_autoadd_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_bool(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_compiled_module(CompiledModule raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_compiled_module(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_func_ty(FuncTy raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_func_ty(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_function_call(FunctionCall raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_function_call(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_global_ty(GlobalTy raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_global_ty(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_64(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_memory_ty(MemoryTy raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_memory_ty(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_module_config(ModuleConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_module_config(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_module_config_wasmi(ModuleConfigWasmi raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_module_config_wasmi(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_module_config_wasmtime(
    ModuleConfigWasmtime raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_module_config_wasmtime(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_table_args(TableArgs raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_table_args(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_table_ty(TableTy raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_table_ty(raw);
  }

  @protected
  int cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_32(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_64(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_wasi_config_native(WasiConfigNative raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_wasi_config_native(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_wasi_stack_limits(WasiStackLimits raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_wasi_stack_limits(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_wasm_run_instance_id(WasmRunInstanceId raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_wasm_run_instance_id(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_wasm_run_module_id(WasmRunModuleId raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_wasm_run_module_id(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_wasm_run_shared_memory(WasmRunSharedMemory raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_wasm_run_shared_memory(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_wasm_val(WasmVal raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_wasm_val(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_wasm_wasi_features(WasmWasiFeatures raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_wasm_wasi_features(raw);
  }

  @protected
  JSAny cst_encode_compare_exchange_result(CompareExchangeResult raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_bool(raw.success), cst_encode_i_64(raw.value)].jsify()!;
  }

  @protected
  JSAny cst_encode_compiled_module(CompiledModule raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_RustOpaque_ArcstdsyncMutexModule(raw.field0)].jsify()!;
  }

  @protected
  JSAny cst_encode_env_variable(EnvVariable raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_String(raw.name), cst_encode_String(raw.value)].jsify()!;
  }

  @protected
  JSAny cst_encode_external_type(ExternalType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is ExternalType_Func) {
      return [0, cst_encode_box_autoadd_func_ty(raw.field0)].jsify()!;
    }
    if (raw is ExternalType_Global) {
      return [1, cst_encode_box_autoadd_global_ty(raw.field0)].jsify()!;
    }
    if (raw is ExternalType_Table) {
      return [2, cst_encode_box_autoadd_table_ty(raw.field0)].jsify()!;
    }
    if (raw is ExternalType_Memory) {
      return [3, cst_encode_box_autoadd_memory_ty(raw.field0)].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_external_value(ExternalValue raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is ExternalValue_Func) {
      return [0, cst_encode_RustOpaque_WFunc(raw.field0)].jsify()!;
    }
    if (raw is ExternalValue_Global) {
      return [1, cst_encode_RustOpaque_Global(raw.field0)].jsify()!;
    }
    if (raw is ExternalValue_Table) {
      return [2, cst_encode_RustOpaque_Table(raw.field0)].jsify()!;
    }
    if (raw is ExternalValue_Memory) {
      return [3, cst_encode_RustOpaque_Memory(raw.field0)].jsify()!;
    }
    if (raw is ExternalValue_SharedMemory) {
      return [
        4,
        cst_encode_box_autoadd_wasm_run_shared_memory(raw.field0),
      ].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_func_ty(FuncTy raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_value_ty(raw.parameters),
      cst_encode_list_value_ty(raw.results),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_function_call(FunctionCall raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_list_wasm_val(raw.args),
      cst_encode_u_32(raw.functionId),
      cst_encode_usize(raw.functionPointer),
      cst_encode_usize(raw.numResults),
      cst_encode_usize(raw.workerIndex),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_global_ty(GlobalTy raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_value_ty(raw.value),
      cst_encode_bool(raw.mutable),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_env_variable(List<EnvVariable> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_env_variable).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_module_export_desc(List<ModuleExportDesc> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_module_export_desc).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_module_export_value(List<ModuleExportValue> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_module_export_value).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_module_import(List<ModuleImport> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_module_import).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_module_import_desc(List<ModuleImportDesc> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_module_import_desc).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_preopened_dir(List<PreopenedDir> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_preopened_dir).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_loose(List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_value_ty(List<ValueTy> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_value_ty).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_wasm_val(List<WasmVal> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_wasm_val).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_memory_ty(MemoryTy raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.shared),
      cst_encode_u_32(raw.minimum),
      cst_encode_opt_box_autoadd_u_32(raw.maximum),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_module_config(ModuleConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_box_autoadd_bool(raw.multiValue),
      cst_encode_opt_box_autoadd_bool(raw.bulkMemory),
      cst_encode_opt_box_autoadd_bool(raw.referenceTypes),
      cst_encode_opt_box_autoadd_bool(raw.consumeFuel),
      cst_encode_opt_box_autoadd_module_config_wasmi(raw.wasmi),
      cst_encode_opt_box_autoadd_module_config_wasmtime(raw.wasmtime),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_module_config_wasmi(ModuleConfigWasmi raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_box_autoadd_wasi_stack_limits(raw.stackLimits),
      cst_encode_opt_box_autoadd_i_64(raw.cachedStacks),
      cst_encode_opt_box_autoadd_bool(raw.mutableGlobal),
      cst_encode_opt_box_autoadd_bool(raw.signExtension),
      cst_encode_opt_box_autoadd_bool(raw.saturatingFloatToInt),
      cst_encode_opt_box_autoadd_bool(raw.tailCall),
      cst_encode_opt_box_autoadd_bool(raw.extendedConst),
      cst_encode_opt_box_autoadd_bool(raw.floats),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_module_config_wasmtime(ModuleConfigWasmtime raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_box_autoadd_bool(raw.debugInfo),
      cst_encode_opt_box_autoadd_bool(raw.wasmBacktrace),
      cst_encode_opt_box_autoadd_bool(raw.nativeUnwindInfo),
      cst_encode_opt_box_autoadd_i_64(raw.maxWasmStack),
      cst_encode_opt_box_autoadd_bool(raw.wasmThreads),
      cst_encode_opt_box_autoadd_bool(raw.wasmSimd),
      cst_encode_opt_box_autoadd_bool(raw.wasmRelaxedSimd),
      cst_encode_opt_box_autoadd_bool(raw.relaxedSimdDeterministic),
      cst_encode_opt_box_autoadd_bool(raw.wasmMultiMemory),
      cst_encode_opt_box_autoadd_bool(raw.wasmMemory64),
      cst_encode_opt_box_autoadd_u_64(raw.staticMemoryMaximumSize),
      cst_encode_opt_box_autoadd_bool(raw.staticMemoryForced),
      cst_encode_opt_box_autoadd_u_64(raw.staticMemoryGuardSize),
      cst_encode_opt_box_autoadd_bool(raw.parallelCompilation),
      cst_encode_opt_box_autoadd_bool(raw.generateAddressMap),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_module_export_desc(ModuleExportDesc raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.name),
      cst_encode_external_type(raw.ty),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_module_export_value(ModuleExportValue raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_module_export_desc(raw.desc),
      cst_encode_external_value(raw.value),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_module_import(ModuleImport raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.module),
      cst_encode_String(raw.name),
      cst_encode_external_value(raw.value),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_module_import_desc(ModuleImportDesc raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.module),
      cst_encode_String(raw.name),
      cst_encode_external_type(raw.ty),
    ].jsify()!;
  }

  @protected
  int? cst_encode_opt_box_autoadd_RustOpaque_WFunc(WFunc? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_RustOpaque_WFunc(raw);
  }

  @protected
  bool? cst_encode_opt_box_autoadd_bool(bool? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_bool(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_module_config_wasmi(
    ModuleConfigWasmi? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_module_config_wasmi(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_module_config_wasmtime(
    ModuleConfigWasmtime? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? null
        : cst_encode_box_autoadd_module_config_wasmtime(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_u_64(BigInt? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_64(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_wasi_config_native(WasiConfigNative? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_wasi_config_native(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_wasi_stack_limits(WasiStackLimits? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_wasi_stack_limits(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_wasm_val(WasmVal? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_wasm_val(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_wasm_wasi_features(WasmWasiFeatures? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_wasm_wasi_features(raw);
  }

  @protected
  JSAny cst_encode_parallel_exec(ParallelExec raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is ParallelExec_Ok) {
      return [0, cst_encode_list_wasm_val(raw.field0)].jsify()!;
    }
    if (raw is ParallelExec_Err) {
      return [1, cst_encode_String(raw.field0)].jsify()!;
    }
    if (raw is ParallelExec_Call) {
      return [2, cst_encode_box_autoadd_function_call(raw.field0)].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_pointer_and_length(PointerAndLength raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_i_64(raw.pointer), cst_encode_i_64(raw.length)].jsify()!;
  }

  @protected
  JSAny cst_encode_preopened_dir(PreopenedDir raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.wasmGuestPath),
      cst_encode_String(raw.hostPath),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_table_args(TableArgs raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_32(raw.minimum),
      cst_encode_opt_box_autoadd_u_32(raw.maximum),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_table_ty(TableTy raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_value_ty(raw.element),
      cst_encode_u_32(raw.minimum),
      cst_encode_opt_box_autoadd_u_32(raw.maximum),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_u_8_array_16(U8Array16 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return Uint8List.fromList(raw).jsify()!;
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_wasi_config_native(WasiConfigNative raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.captureStdout),
      cst_encode_bool(raw.captureStderr),
      cst_encode_bool(raw.inheritStdin),
      cst_encode_bool(raw.inheritEnv),
      cst_encode_bool(raw.inheritArgs),
      cst_encode_list_String(raw.args),
      cst_encode_list_env_variable(raw.env),
      cst_encode_list_String(raw.preopenedFiles),
      cst_encode_list_preopened_dir(raw.preopenedDirs),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_wasi_stack_limits(WasiStackLimits raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_i_64(raw.initialValueStackHeight),
      cst_encode_i_64(raw.maximumValueStackHeight),
      cst_encode_i_64(raw.maximumRecursionDepth),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_wasm_features(WasmFeatures raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.mutableGlobal),
      cst_encode_bool(raw.saturatingFloatToInt),
      cst_encode_bool(raw.signExtension),
      cst_encode_bool(raw.referenceTypes),
      cst_encode_bool(raw.multiValue),
      cst_encode_bool(raw.bulkMemory),
      cst_encode_bool(raw.simd),
      cst_encode_bool(raw.relaxedSimd),
      cst_encode_bool(raw.threads),
      cst_encode_bool(raw.tailCall),
      cst_encode_bool(raw.floats),
      cst_encode_bool(raw.multiMemory),
      cst_encode_bool(raw.exceptions),
      cst_encode_bool(raw.memory64),
      cst_encode_bool(raw.extendedConst),
      cst_encode_bool(raw.componentModel),
      cst_encode_bool(raw.memoryControl),
      cst_encode_bool(raw.garbageCollection),
      cst_encode_bool(raw.typeReflection),
      cst_encode_opt_box_autoadd_wasm_wasi_features(raw.wasiFeatures),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_wasm_run_instance_id(WasmRunInstanceId raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_u_32(raw.field0)].jsify()!;
  }

  @protected
  JSAny cst_encode_wasm_run_module_id(WasmRunModuleId raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_32(raw.field0),
      cst_encode_RustOpaque_CallStack(raw.field1),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_wasm_run_shared_memory(WasmRunSharedMemory raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_RustOpaque_ArcRwLockSharedMemory(raw.field0)].jsify()!;
  }

  @protected
  JSAny cst_encode_wasm_runtime_features(WasmRuntimeFeatures raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.name),
      cst_encode_String(raw.version),
      cst_encode_bool(raw.isBrowser),
      cst_encode_wasm_features(raw.supportedFeatures),
      cst_encode_wasm_features(raw.defaultFeatures),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_wasm_val(WasmVal raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is WasmVal_i32) {
      return [0, cst_encode_i_32(raw.field0)].jsify()!;
    }
    if (raw is WasmVal_i64) {
      return [1, cst_encode_i_64(raw.field0)].jsify()!;
    }
    if (raw is WasmVal_f32) {
      return [2, cst_encode_f_32(raw.field0)].jsify()!;
    }
    if (raw is WasmVal_f64) {
      return [3, cst_encode_f_64(raw.field0)].jsify()!;
    }
    if (raw is WasmVal_v128) {
      return [4, cst_encode_u_8_array_16(raw.field0)].jsify()!;
    }
    if (raw is WasmVal_funcRef) {
      return [
        5,
        cst_encode_opt_box_autoadd_RustOpaque_WFunc(raw.field0),
      ].jsify()!;
    }
    if (raw is WasmVal_externRef) {
      return [6, cst_encode_opt_box_autoadd_u_32(raw.field0)].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_wasm_wasi_features(WasmWasiFeatures raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_bool(raw.io),
      cst_encode_bool(raw.filesystem),
      cst_encode_bool(raw.clocks),
      cst_encode_bool(raw.random),
      cst_encode_bool(raw.poll),
      cst_encode_bool(raw.machineLearning),
      cst_encode_bool(raw.crypto),
      cst_encode_bool(raw.threads),
    ].jsify()!;
  }

  @protected
  int cst_encode_RustOpaque_ArcRwLockSharedMemory(ArcRwLockSharedMemory raw);

  @protected
  int cst_encode_RustOpaque_ArcstdsyncMutexModule(ArcMutexModule raw);

  @protected
  int cst_encode_RustOpaque_CallStack(CallStack raw);

  @protected
  int cst_encode_RustOpaque_Global(Global raw);

  @protected
  int cst_encode_RustOpaque_Memory(Memory raw);

  @protected
  int cst_encode_RustOpaque_Table(Table raw);

  @protected
  int cst_encode_RustOpaque_WFunc(WFunc raw);

  @protected
  int cst_encode_atomic_kind(AtomicKind raw);

  @protected
  int cst_encode_atomic_ordering(AtomicOrdering raw);

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_32(double raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_shared_memory_wait_result(SharedMemoryWaitResult raw);

  @protected
  int cst_encode_std_io_kind(StdIOKind raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  int cst_encode_value_ty(ValueTy raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_ArcRwLockSharedMemory(
    ArcRwLockSharedMemory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_ArcstdsyncMutexModule(
    ArcMutexModule self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_CallStack(
    CallStack self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_Global(Global self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_Memory(Memory self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_Table(Table self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_WFunc(WFunc self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Dco(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_parallel_exec_Dco(
    RustStreamSink<ParallelExec> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_atomic_kind(AtomicKind self, SseSerializer serializer);

  @protected
  void sse_encode_atomic_ordering(
    AtomicOrdering self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_atomics(Atomics self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_RustOpaque_WFunc(
    WFunc self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_atomics(Atomics self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_compiled_module(
    CompiledModule self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_func_ty(FuncTy self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_function_call(
    FunctionCall self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_global_ty(
    GlobalTy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_memory_ty(
    MemoryTy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_module_config(
    ModuleConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_module_config_wasmi(
    ModuleConfigWasmi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_module_config_wasmtime(
    ModuleConfigWasmtime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_table_args(
    TableArgs self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_table_ty(TableTy self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_wasi_config_native(
    WasiConfigNative self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wasi_stack_limits(
    WasiStackLimits self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wasm_run_instance_id(
    WasmRunInstanceId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wasm_run_module_id(
    WasmRunModuleId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wasm_run_shared_memory(
    WasmRunSharedMemory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_wasm_val(WasmVal self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_wasm_wasi_features(
    WasmWasiFeatures self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_compare_exchange_result(
    CompareExchangeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_compiled_module(
    CompiledModule self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_env_variable(EnvVariable self, SseSerializer serializer);

  @protected
  void sse_encode_external_type(ExternalType self, SseSerializer serializer);

  @protected
  void sse_encode_external_value(ExternalValue self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_func_ty(FuncTy self, SseSerializer serializer);

  @protected
  void sse_encode_function_call(FunctionCall self, SseSerializer serializer);

  @protected
  void sse_encode_global_ty(GlobalTy self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_env_variable(
    List<EnvVariable> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_module_export_desc(
    List<ModuleExportDesc> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_module_export_value(
    List<ModuleExportValue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_module_import(
    List<ModuleImport> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_module_import_desc(
    List<ModuleImportDesc> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_preopened_dir(
    List<PreopenedDir> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_value_ty(List<ValueTy> self, SseSerializer serializer);

  @protected
  void sse_encode_list_wasm_val(List<WasmVal> self, SseSerializer serializer);

  @protected
  void sse_encode_memory_ty(MemoryTy self, SseSerializer serializer);

  @protected
  void sse_encode_module_config(ModuleConfig self, SseSerializer serializer);

  @protected
  void sse_encode_module_config_wasmi(
    ModuleConfigWasmi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_module_config_wasmtime(
    ModuleConfigWasmtime self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_module_export_desc(
    ModuleExportDesc self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_module_export_value(
    ModuleExportValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_module_import(ModuleImport self, SseSerializer serializer);

  @protected
  void sse_encode_module_import_desc(
    ModuleImportDesc self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_RustOpaque_WFunc(
    WFunc? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_module_config_wasmi(
    ModuleConfigWasmi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_module_config_wasmtime(
    ModuleConfigWasmtime? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_wasi_config_native(
    WasiConfigNative? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_wasi_stack_limits(
    WasiStackLimits? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_wasm_val(
    WasmVal? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_wasm_wasi_features(
    WasmWasiFeatures? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parallel_exec(ParallelExec self, SseSerializer serializer);

  @protected
  void sse_encode_pointer_and_length(
    PointerAndLength self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_preopened_dir(PreopenedDir self, SseSerializer serializer);

  @protected
  void sse_encode_shared_memory_wait_result(
    SharedMemoryWaitResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_std_io_kind(StdIOKind self, SseSerializer serializer);

  @protected
  void sse_encode_table_args(TableArgs self, SseSerializer serializer);

  @protected
  void sse_encode_table_ty(TableTy self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8_array_16(U8Array16 self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_value_ty(ValueTy self, SseSerializer serializer);

  @protected
  void sse_encode_wasi_config_native(
    WasiConfigNative self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wasi_stack_limits(
    WasiStackLimits self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wasm_features(WasmFeatures self, SseSerializer serializer);

  @protected
  void sse_encode_wasm_run_instance_id(
    WasmRunInstanceId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wasm_run_module_id(
    WasmRunModuleId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wasm_run_shared_memory(
    WasmRunSharedMemory self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wasm_runtime_features(
    WasmRuntimeFeatures self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wasm_val(WasmVal self, SseSerializer serializer);

  @protected
  void sse_encode_wasm_wasi_features(
    WasmWasiFeatures self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary();

  void wire__crate__atomics__atomics_add(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  ) => wasmModule.wire__crate__atomics__atomics_add(
    port_,
    that,
    offset,
    kind,
    val,
    order,
  );

  void wire__crate__atomics__atomics_and(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  ) => wasmModule.wire__crate__atomics__atomics_and(
    port_,
    that,
    offset,
    kind,
    val,
    order,
  );

  void wire__crate__atomics__atomics_compare_exchange(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny current,
    JSAny new_value,
    int success,
    int failure,
  ) => wasmModule.wire__crate__atomics__atomics_compare_exchange(
    port_,
    that,
    offset,
    kind,
    current,
    new_value,
    success,
    failure,
  );

  void wire__crate__atomics__atomics_load(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    int order,
  ) => wasmModule.wire__crate__atomics__atomics_load(
    port_,
    that,
    offset,
    kind,
    order,
  );

  void wire__crate__atomics__atomics_or(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  ) => wasmModule.wire__crate__atomics__atomics_or(
    port_,
    that,
    offset,
    kind,
    val,
    order,
  );

  void wire__crate__atomics__atomics_store(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  ) => wasmModule.wire__crate__atomics__atomics_store(
    port_,
    that,
    offset,
    kind,
    val,
    order,
  );

  void wire__crate__atomics__atomics_sub(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  ) => wasmModule.wire__crate__atomics__atomics_sub(
    port_,
    that,
    offset,
    kind,
    val,
    order,
  );

  void wire__crate__atomics__atomics_swap(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  ) => wasmModule.wire__crate__atomics__atomics_swap(
    port_,
    that,
    offset,
    kind,
    val,
    order,
  );

  void wire__crate__atomics__atomics_xor(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  ) => wasmModule.wire__crate__atomics__atomics_xor(
    port_,
    that,
    offset,
    kind,
    val,
    order,
  );

  void wire__crate__api__compile_wasm(
    NativePortType port_,
    JSAny module_wasm,
    JSAny config,
  ) => wasmModule.wire__crate__api__compile_wasm(port_, module_wasm, config);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__compile_wasm_sync(JSAny module_wasm, JSAny config) =>
      wasmModule.wire__crate__api__compile_wasm_sync(module_wasm, config);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__compiled_module_create_shared_memory(
    JSAny that,
    JSAny memory_type,
  ) => wasmModule.wire__crate__api__compiled_module_create_shared_memory(
    that,
    memory_type,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__compiled_module_get_module_exports(JSAny that) =>
      wasmModule.wire__crate__api__compiled_module_get_module_exports(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__compiled_module_get_module_imports(JSAny that) =>
      wasmModule.wire__crate__api__compiled_module_get_module_imports(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__module_builder(
    JSAny module,
    int? num_threads,
    JSAny? wasi_config,
  ) => wasmModule.wire__crate__api__module_builder(
    module,
    num_threads,
    wasi_config,
  );

  void wire__crate__api__parse_wat_format(NativePortType port_, String wat) =>
      wasmModule.wire__crate__api__parse_wat_format(port_, wat);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_features_for_config(JSAny config) =>
      wasmModule.wire__crate__api__wasm_features_for_config(config);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_instance_id_exports(JSAny that) =>
      wasmModule.wire__crate__api__wasm_run_instance_id_exports(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_add_fuel(JSAny that, JSAny delta) =>
      wasmModule.wire__crate__api__wasm_run_module_id_add_fuel(that, delta);

  void wire__crate__api__wasm_run_module_id_call_function_handle(
    NativePortType port_,
    JSAny that,
    int func,
    JSAny args,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_call_function_handle(
    port_,
    that,
    func,
    args,
  );

  void wire__crate__api__wasm_run_module_id_call_function_handle_parallel(
    NativePortType port_,
    JSAny that,
    String func_name,
    JSAny args,
    int num_tasks,
    String function_stream,
  ) => wasmModule
      .wire__crate__api__wasm_run_module_id_call_function_handle_parallel(
        port_,
        that,
        func_name,
        args,
        num_tasks,
        function_stream,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_call_function_handle_sync(
    JSAny that,
    int func,
    JSAny args,
  ) =>
      wasmModule.wire__crate__api__wasm_run_module_id_call_function_handle_sync(
        that,
        func,
        args,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_consume_fuel(JSAny that, JSAny delta) =>
      wasmModule.wire__crate__api__wasm_run_module_id_consume_fuel(that, delta);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_create_function(
    JSAny that,
    JSAny function_pointer,
    int function_id,
    JSAny param_types,
    JSAny result_types,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_create_function(
    that,
    function_pointer,
    function_id,
    param_types,
    result_types,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_create_global(
    JSAny that,
    JSAny value,
    bool mutable,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_create_global(
    that,
    value,
    mutable,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_create_memory(
    JSAny that,
    JSAny memory_type,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_create_memory(
    that,
    memory_type,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_create_table(
    JSAny that,
    JSAny value,
    JSAny table_type,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_create_table(
    that,
    value,
    table_type,
  );

  void wire__crate__api__wasm_run_module_id_dispose(
    NativePortType port_,
    JSAny that,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_dispose(port_, that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_fill_table(
    JSAny that,
    int table,
    int index,
    JSAny value,
    int len,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_fill_table(
    that,
    table,
    index,
    value,
    len,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_fuel_consumed(JSAny that) =>
      wasmModule.wire__crate__api__wasm_run_module_id_fuel_consumed(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_function_type(
    JSAny that,
    int func,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_get_function_type(
    that,
    func,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_global_type(
    JSAny that,
    int global,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_get_global_type(
    that,
    global,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_global_value(
    JSAny that,
    int global,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_get_global_value(
    that,
    global,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_memory_data(
    JSAny that,
    int memory,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_get_memory_data(
    that,
    memory,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_memory_data_pointer(
    JSAny that,
    int memory,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_get_memory_data_pointer(
    that,
    memory,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_memory_data_pointer_and_length(
    JSAny that,
    int memory,
  ) => wasmModule
      .wire__crate__api__wasm_run_module_id_get_memory_data_pointer_and_length(
        that,
        memory,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_memory_pages(
    JSAny that,
    int memory,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_get_memory_pages(
    that,
    memory,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_memory_type(
    JSAny that,
    int memory,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_get_memory_type(
    that,
    memory,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_table(
    JSAny that,
    int table,
    int index,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_get_table(
    that,
    table,
    index,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_table_size(JSAny that, int table) =>
      wasmModule.wire__crate__api__wasm_run_module_id_get_table_size(
        that,
        table,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_table_type(JSAny that, int table) =>
      wasmModule.wire__crate__api__wasm_run_module_id_get_table_type(
        that,
        table,
      );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_grow_memory(
    JSAny that,
    int memory,
    int pages,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_grow_memory(
    that,
    memory,
    pages,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_grow_table(
    JSAny that,
    int table,
    int delta,
    JSAny value,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_grow_table(
    that,
    table,
    delta,
    value,
  );

  void wire__crate__api__wasm_run_module_id_instantiate(
    NativePortType port_,
    JSAny that,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_instantiate(port_, that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_instantiate_sync(JSAny that) =>
      wasmModule.wire__crate__api__wasm_run_module_id_instantiate_sync(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_link_imports(
    JSAny that,
    JSAny imports,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_link_imports(
    that,
    imports,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_read_memory(
    JSAny that,
    int memory,
    JSAny offset,
    JSAny bytes,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_read_memory(
    that,
    memory,
    offset,
    bytes,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_set_global_value(
    JSAny that,
    int global,
    JSAny value,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_set_global_value(
    that,
    global,
    value,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_set_table(
    JSAny that,
    int table,
    int index,
    JSAny value,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_set_table(
    that,
    table,
    index,
    value,
  );

  void wire__crate__api__wasm_run_module_id_stdio_stream(
    NativePortType port_,
    JSAny that,
    String sink,
    int kind,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_stdio_stream(
    port_,
    that,
    sink,
    kind,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_worker_execution(
    JSAny that,
    int worker_index,
    JSAny results,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_worker_execution(
    that,
    worker_index,
    results,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_write_memory(
    JSAny that,
    int memory,
    JSAny offset,
    JSAny buffer,
  ) => wasmModule.wire__crate__api__wasm_run_module_id_write_memory(
    that,
    memory,
    offset,
    buffer,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_atomic_notify(
    JSAny that,
    JSAny addr,
    int count,
  ) => wasmModule.wire__crate__api__wasm_run_shared_memory_atomic_notify(
    that,
    addr,
    count,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_atomic_wait32(
    JSAny that,
    JSAny addr,
    int expected,
  ) => wasmModule.wire__crate__api__wasm_run_shared_memory_atomic_wait32(
    that,
    addr,
    expected,
  );

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_atomic_wait64(
    JSAny that,
    JSAny addr,
    JSAny expected,
  ) => wasmModule.wire__crate__api__wasm_run_shared_memory_atomic_wait64(
    that,
    addr,
    expected,
  );

  void wire__crate__api__wasm_run_shared_memory_atomics(
    NativePortType port_,
    JSAny that,
  ) => wasmModule.wire__crate__api__wasm_run_shared_memory_atomics(port_, that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_data_pointer(JSAny that) =>
      wasmModule.wire__crate__api__wasm_run_shared_memory_data_pointer(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_data_size(JSAny that) =>
      wasmModule.wire__crate__api__wasm_run_shared_memory_data_size(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_grow(JSAny that, JSAny delta) =>
      wasmModule.wire__crate__api__wasm_run_shared_memory_grow(that, delta);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_size(JSAny that) =>
      wasmModule.wire__crate__api__wasm_run_shared_memory_size(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_ty(JSAny that) =>
      wasmModule.wire__crate__api__wasm_run_shared_memory_ty(that);

  JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_runtime_features() =>
      wasmModule.wire__crate__api__wasm_runtime_features();

  void rust_arc_increment_strong_count_RustOpaque_ArcRwLockSharedMemory(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_ArcRwLockSharedMemory(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_ArcRwLockSharedMemory(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_ArcRwLockSharedMemory(ptr);

  void rust_arc_increment_strong_count_RustOpaque_ArcstdsyncMutexModule(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_ArcstdsyncMutexModule(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_ArcstdsyncMutexModule(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_ArcstdsyncMutexModule(ptr);

  void rust_arc_increment_strong_count_RustOpaque_CallStack(int ptr) =>
      wasmModule.rust_arc_increment_strong_count_RustOpaque_CallStack(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_CallStack(int ptr) =>
      wasmModule.rust_arc_decrement_strong_count_RustOpaque_CallStack(ptr);

  void rust_arc_increment_strong_count_RustOpaque_Global(int ptr) =>
      wasmModule.rust_arc_increment_strong_count_RustOpaque_Global(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_Global(int ptr) =>
      wasmModule.rust_arc_decrement_strong_count_RustOpaque_Global(ptr);

  void rust_arc_increment_strong_count_RustOpaque_Memory(int ptr) =>
      wasmModule.rust_arc_increment_strong_count_RustOpaque_Memory(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_Memory(int ptr) =>
      wasmModule.rust_arc_decrement_strong_count_RustOpaque_Memory(ptr);

  void rust_arc_increment_strong_count_RustOpaque_Table(int ptr) =>
      wasmModule.rust_arc_increment_strong_count_RustOpaque_Table(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_Table(int ptr) =>
      wasmModule.rust_arc_decrement_strong_count_RustOpaque_Table(ptr);

  void rust_arc_increment_strong_count_RustOpaque_WFunc(int ptr) =>
      wasmModule.rust_arc_increment_strong_count_RustOpaque_WFunc(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_WFunc(int ptr) =>
      wasmModule.rust_arc_decrement_strong_count_RustOpaque_WFunc(ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__atomics__atomics_add(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  );

  external void wire__crate__atomics__atomics_and(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  );

  external void wire__crate__atomics__atomics_compare_exchange(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny current,
    JSAny new_value,
    int success,
    int failure,
  );

  external void wire__crate__atomics__atomics_load(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    int order,
  );

  external void wire__crate__atomics__atomics_or(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  );

  external void wire__crate__atomics__atomics_store(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  );

  external void wire__crate__atomics__atomics_sub(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  );

  external void wire__crate__atomics__atomics_swap(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  );

  external void wire__crate__atomics__atomics_xor(
    NativePortType port_,
    JSAny that,
    JSAny offset,
    int kind,
    JSAny val,
    int order,
  );

  external void wire__crate__api__compile_wasm(
    NativePortType port_,
    JSAny module_wasm,
    JSAny config,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__compile_wasm_sync(JSAny module_wasm, JSAny config);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__compiled_module_create_shared_memory(
    JSAny that,
    JSAny memory_type,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__compiled_module_get_module_exports(JSAny that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__compiled_module_get_module_imports(JSAny that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__module_builder(
    JSAny module,
    int? num_threads,
    JSAny? wasi_config,
  );

  external void wire__crate__api__parse_wat_format(
    NativePortType port_,
    String wat,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_features_for_config(JSAny config);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_instance_id_exports(JSAny that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_add_fuel(JSAny that, JSAny delta);

  external void wire__crate__api__wasm_run_module_id_call_function_handle(
    NativePortType port_,
    JSAny that,
    int func,
    JSAny args,
  );

  external void
  wire__crate__api__wasm_run_module_id_call_function_handle_parallel(
    NativePortType port_,
    JSAny that,
    String func_name,
    JSAny args,
    int num_tasks,
    String function_stream,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_call_function_handle_sync(
    JSAny that,
    int func,
    JSAny args,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_consume_fuel(JSAny that, JSAny delta);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_create_function(
    JSAny that,
    JSAny function_pointer,
    int function_id,
    JSAny param_types,
    JSAny result_types,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_create_global(
    JSAny that,
    JSAny value,
    bool mutable,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_create_memory(
    JSAny that,
    JSAny memory_type,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_create_table(
    JSAny that,
    JSAny value,
    JSAny table_type,
  );

  external void wire__crate__api__wasm_run_module_id_dispose(
    NativePortType port_,
    JSAny that,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_fill_table(
    JSAny that,
    int table,
    int index,
    JSAny value,
    int len,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_fuel_consumed(JSAny that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_function_type(JSAny that, int func);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_global_type(JSAny that, int global);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_global_value(JSAny that, int global);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_memory_data(JSAny that, int memory);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_memory_data_pointer(
    JSAny that,
    int memory,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_memory_data_pointer_and_length(
    JSAny that,
    int memory,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_memory_pages(JSAny that, int memory);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_memory_type(JSAny that, int memory);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_table(
    JSAny that,
    int table,
    int index,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_table_size(JSAny that, int table);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_get_table_type(JSAny that, int table);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_grow_memory(
    JSAny that,
    int memory,
    int pages,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_grow_table(
    JSAny that,
    int table,
    int delta,
    JSAny value,
  );

  external void wire__crate__api__wasm_run_module_id_instantiate(
    NativePortType port_,
    JSAny that,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_instantiate_sync(JSAny that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_link_imports(JSAny that, JSAny imports);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_read_memory(
    JSAny that,
    int memory,
    JSAny offset,
    JSAny bytes,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_set_global_value(
    JSAny that,
    int global,
    JSAny value,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_set_table(
    JSAny that,
    int table,
    int index,
    JSAny value,
  );

  external void wire__crate__api__wasm_run_module_id_stdio_stream(
    NativePortType port_,
    JSAny that,
    String sink,
    int kind,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_worker_execution(
    JSAny that,
    int worker_index,
    JSAny results,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_module_id_write_memory(
    JSAny that,
    int memory,
    JSAny offset,
    JSAny buffer,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_atomic_notify(
    JSAny that,
    JSAny addr,
    int count,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_atomic_wait32(
    JSAny that,
    JSAny addr,
    int expected,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_atomic_wait64(
    JSAny that,
    JSAny addr,
    JSAny expected,
  );

  external void wire__crate__api__wasm_run_shared_memory_atomics(
    NativePortType port_,
    JSAny that,
  );

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_data_pointer(JSAny that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_data_size(JSAny that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_grow(JSAny that, JSAny delta);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_size(JSAny that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_run_shared_memory_ty(JSAny that);

  external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */
  wire__crate__api__wasm_runtime_features();

  external void
  rust_arc_increment_strong_count_RustOpaque_ArcRwLockSharedMemory(int ptr);

  external void
  rust_arc_decrement_strong_count_RustOpaque_ArcRwLockSharedMemory(int ptr);

  external void
  rust_arc_increment_strong_count_RustOpaque_ArcstdsyncMutexModule(int ptr);

  external void
  rust_arc_decrement_strong_count_RustOpaque_ArcstdsyncMutexModule(int ptr);

  external void rust_arc_increment_strong_count_RustOpaque_CallStack(int ptr);

  external void rust_arc_decrement_strong_count_RustOpaque_CallStack(int ptr);

  external void rust_arc_increment_strong_count_RustOpaque_Global(int ptr);

  external void rust_arc_decrement_strong_count_RustOpaque_Global(int ptr);

  external void rust_arc_increment_strong_count_RustOpaque_Memory(int ptr);

  external void rust_arc_decrement_strong_count_RustOpaque_Memory(int ptr);

  external void rust_arc_increment_strong_count_RustOpaque_Table(int ptr);

  external void rust_arc_decrement_strong_count_RustOpaque_Table(int ptr);

  external void rust_arc_increment_strong_count_RustOpaque_WFunc(int ptr);

  external void rust_arc_decrement_strong_count_RustOpaque_WFunc(int ptr);
}
