name: wasm_run_native
description: |
  Native WebAssembly runtime library for wasm_run.
  Builds wasmtime/wasmi from Rust source via Cargokit.
version: 0.1.0
homepage: https://github.com/juancastillo0/wasm_run

topics:
  - wasm
  - interop
  - runtime
  - ffi

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
