name: wasm_run_example
description: Demonstrates how to use the wasm_run package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0
resolution: workspace

dependencies:
  wasm_run:
    path: ../
  wasm_wit_component_example:
    path: ../../dart_wit_component/wasm_wit_component/example
  test: ^1.21.0

dev_dependencies:
  very_good_analysis: ^10.0.0