name: wasm_run_example
description: Demonstrates how to use the wasm_run package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  test: ^1.26.0
  wasm_run:
    path: ../
  wasm_wit_component_example:
    path: ../../dart_wit_component/wasm_wit_component/example

dev_dependencies:
  very_good_analysis: ^10.0.0
